version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nais-denki-web
    environment:
      RAILS_ENV: development
    volumes:
      - ./nais-denki-web:/app/nais-denki-web:rw
      - ./start_app.sh:/usr/local/bin/start_app.sh:ro
    ports:
      - 3000:3000
    working_dir: /app/nais-denki-web
    command: bash /usr/local/bin/start_app.sh
  db:
    image: mariadb:latest
    container_name: nais-denki-db
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: nais-denki-web_development
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: nais_denki
      MYSQL_PASSWORD: password

